spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/UserDB
    username: test
    password: test

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    mapper:
      accept-case-insensitive-enums: true

  security:
    user:
      name: test
      password: test

redis:
  hostName: localhost

jwt:
  secret-key: 68576D5A7134743777217A25432A462D4A404E635266556A586E327235753878
  expiration: 86400000

socket:
  host-name: 0.0.0.0
  port: 9090

logging:
  level:
    tracer: TRACE
    org.zalando.logbook: TRACE
    org.hibernate.SQL: DEBUG
    com.netflix.eureka: 'OFF'
    org.elasticsearch.client.RestClient: ERROR

