spring:
  datasource:
    url: jdbc:h2:mem:USER_DB
    username: test
    password: test

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  jackson:
    mapper:
      accept-case-insensitive-enums: true